language: scala

scala:
  - 2.11.12

script:
  - sbt ++$TRAVIS_SCALA_VERSION "run https://repo1.maven.org"

jdk:
  - openjdk6
  - oraclejdk8

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
