sudo: required

language: scala

scala:
  - 2.11.12

script:
  # work around https://github.com/travis-ci/travis-ci/issues/9713
  - if [[ $JAVA_HOME = *java-6* ]]; then jdk_switcher use openjdk6; fi
  - java -version
  - sbt ++$TRAVIS_SCALA_VERSION "run https://repo1.maven.org"

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - oraclejdk8

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
